stages:
  precompute-tree:
    foreach:
      - n: 3
        start: cross
      - n: 3
        start: circle
    do:
      cmd: python ./precompute_tree.py -n ${item.n} --start_player ${item.start} --out_dir ./trees/${item.n}/${item.start}
      deps:
        - ./precompute_tree.py
      outs:
        - ./trees/${item.n}/${item.start}