stages:
  precompute-minmax-tree:
    vars:
      - ./configs/minmax_precompute.yaml:out_dir
    cmd: python ./precompute_tree.py
    deps:
      - ./precompute_tree.py
      - ./configs/minmax_precompute.yaml
    outs:
      - ${out_dir}

  precompute-mcts-cross:
    vars:
      - out_dir: ./trees/mcts/4/cross
    cmd: python ./precompute_mctc_tree.py out_dir=${out_dir} cross_policy.tree.env=\${env}
    deps:
      - ./precompute_mctc_tree.py
      - ./configs/mcts_precompute.yaml
    params:
      - ./configs/mcts_precompute.yaml:
          - num_simulation
    outs:
      - ${out_dir}

  precompute-mcts-circle:
    vars:
      - out_dir: ./trees/mcts/4/circle 
    cmd: python ./precompute_mctc_tree.py out_dir=${out_dir} cross_policy=random circle_policy=mcts_tree circle_policy.tree.env=\${env}
    deps:
      - ./precompute_mctc_tree.py
      - ./configs/mcts_precompute.yaml
    params:
      - ./configs/mcts_precompute.yaml:
          - num_simulation
    outs:
      - ${out_dir}

  precompute-states-3x3-cross:
    vars:
      - out_path: ./stat/3/cross_stat.json 
    cmd: python ./generate_all_states.py start_player=1 state_file=${out_path}
    deps:
      - ./generate_all_states.py
      - ./configs/generate_states.yaml
      - ./trees/minmax/3/cross/3_3_3_start_1.pickle
    outs:
      - ${out_path}
  
  precompute-states-3x3-circle:
    vars:
      - out_path: ./stat/3/circle_stat.json 
    cmd: python ./generate_all_states.py start_player=-1 state_file=${out_path}
    deps:
      - ./generate_all_states.py
      - ./configs/generate_states.yaml
      - ./trees/minmax/3/cross/3_3_3_start_1.pickle
    outs:
      - ${out_path}

  compute-minmax-game-cross-minmax:
    vars:
      - ./configs/simulate.yaml
      - out_dir: stat/cross_minmax_vs_random/
      - tree_file: ./trees/minmax/3/cross/3_3_3_start_1.pickle
    cmd: python ./simulate_game.py -m cross_policy=tree_from_dump cross_policy.tree.path_to_file=\${hydra:runtime.cwd}/${tree_file} circle_policy=random random_action_proba=0.9,0.95,0.96,0.97,0.99 hydra.sweep.dir=${out_dir}
    deps:
      - ./simulate_game.py 
      - ./configs/simulate.yaml
      - ${tree_file}
    outs:
      - ${out_dir}
    
  compute-minmax-game-circle-minmax:
    vars:
      - ./configs/simulate.yaml
      - out_dir: stat/cross_random_vs_minmax/
      - tree_file: ./trees/minmax/3/cross/3_3_3_start_1.pickle
    cmd: python ./simulate_game.py -m cross_policy=random circle_policy=tree_from_dump circle_policy.tree.path_to_file=\${hydra:runtime.cwd}/${tree_file} random_action_proba=0.7,0.75,0.85,0.9 hydra.sweep.dir=${out_dir}
    deps:
      - ./simulate_game.py 
      - ./configs/simulate.yaml
      - ${tree_file}
    outs:
      - ${out_dir}
