version: 1
formatters:
  default_console_thread:
    (): log_set.utc_fromatter.UTCFormatter
    format: '%(asctime)s %(levelname)s %(threadName)s %(module)s %(funcName)s %(message)s'
  default_console_process:
    (): log_set.utc_fromatter.UTCFormatter
    format: '%(asctime)s %(levelname)s %(processName)s %(module)s %(funcName)s %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default_console_thread
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    filename: tictoc.log 
    encoding: utf-8
    mode: 'w'
loggers:
  tictoc:
    level: DEBUG
    handlers: [file]
    propagate: no
root:
  level: INFO
  handlers: [console]