name: 'mcts-rollout-dueling-dqn'
object:
  _target_: tictac_rl.policies.policy.TreePolicy
  tree:
    _target_: tictac_rl.utils.load_from_dump
    path_to_file: ${hydra:runtime.cwd}/trees/mcts/4/circle_duoling_dqn/4_4_4_circle_start_1.pickle