hydra:
  run:
    dir: .
  output_subdir: null

defaults:
  - env: env4x4
  - cross_policy: random
  - circle_policy: mcts_with_policy
  - _self_

player_name: circle

circle_policy:
  tree: 
    env: ${env}
    depth_limit: 6
    cross_policy:
      _target_: tictac_rl.policies.policy.RandomPolicy
    circle_policy:
      _target_: tictac_rl.utils.load_from_dump
      path_to_file: ${hydra:runtime.cwd}/exp/table_q_learning/4/${player_name}/6_alpha=0.9_gamma=0.1/policies/${player_name}.pickle


out_dir: ./trees/mcts/4/circle_q_table

num_simulation: 2000
