hydra:
  run:
    dir: .
  sweep:
    dir: stat/game_stats_simulation
    subdir: ${hydra.job.num}_${random_action_proba}

defaults:
  - _self_
  - env: env3x3
  - cross_policy: from_dump
  - circle_policy: from_dump
  - override hydra/launcher: joblib

num_sim: 7000
random_action_proba: 0
metric_file: ./game_stat.json

cross_policy:
  tree:
    path_to_file: ./trees/minmax/3/cross/3_3_3_start_1.pickle

circle_policy:
  tree: ${cross_policy.tree}
