hydra:
  run:
    dir: .
  sweep:
    dir: stat/game_simul/3
    subdir: ${cross_player.name}_vs_${circle_player.name}
  
  launcher:
    n_jobs: 8

defaults:
  - env: env3x3
  - cross_player: random
  - circle_player: random
  - override hydra/launcher: joblib
  - _self_

num_sim: 2000
random_action_proba: 0.09
metric_file: ./game_stat.json

train_config: null
