hydra:
  run:
    dir: .
  sweep:
    dir: ./exp/table_q_learning/cross
    subdir: ${hydra.job.num}_alpha=${learning_rate}_gamma=${gamma}

  launcher:
    n_jobs: 8

defaults:
  - env: env3x3
  - cross_policy: tree_from_dump
  - circle_policy: q_learning
  - override hydra/launcher: joblib
  - _self_

path_to_state: ./stat/3/circle_stat.json
generator:
  _target_: random.Random
  _args_:
    - 786
learning_rate: 0.1
gamma: 0.5
num_train_iterations: 10
num_test_iterations: 10
num_valid_episodes: 10
tree_random_action_proba: 0

exp_dir: .

cross_policy:
  tree:
    path_to_file: ./trees/minmax/3/cross/3_3_3_start_1.pickle