hydra:
  run:
    dir: .
  sweep:
    dir: ./exp/table_q_learning/cross
    subdir: ${hydra.job.num}_alpha=${learning_rate}_gamma=${gamma}

  launcher:
    n_jobs: 3

defaults:
  - env: env3x3
  - cross_policy: q_learning
  - circle_policy: tree_from_dump
  - override hydra/launcher: joblib
  - _self_

path_to_state: null
learning_rate: 0.1
gamma: 0.5
num_train_iterations: 10
num_test_iterations: 10
num_valid_episodes: 10
tree_random_action_proba: 0.99

exp_dir: .

circle_policy:
  tree:
    path_to_file: null