hydra:
  run:
    dir: .
  sweep:
    dir: ./exp/table_q_learning/cross
    subdir: ${hydra.job.num}_alpha=${learning_rate}_gamma=${gamma}

  launcher:
    n_jobs: 12

defaults:
  - env: env3x3
  - cross_policy: q_learning
  - circle_policy: tree_from_dump
  - override hydra/launcher: joblib
  - _self_

learning_rate: 0.1
gamma: 0.2
num_train_iterations: 20000
num_test_iterations: 50
num_valid_episodes: 1000
tree_random_action_proba: 0.09

exp_dir: .