hydra:
  run:
    dir: .
  sweep:
    dir: multirun
    subdir: ${hydra.job.num}_${random_action_proba}
  launcher:
    n_jobs: 8

defaults:
  - env: env3x3
  - cross_policy: q_learning
  - circle_policy: tree_from_dump
  - override hydra/launcher: joblib
  - _self_

path_to_state: ./stat/3/cross_stat.json
learning_rate: 0.1
gamma: 0.5
num_train_iterations: 500_000
num_test_iterations: 100
num_valid_episodes: 10_000
tree_random_action_proba: 0.99

exp_dir: ./exp/table_q_learning/cross

circle_policy:
  tree:
    path_to_file: ./trees/minmax/3/cross/3_3_3_start_1.pickle